package com.ww.geo.region.enums;


import com.ww.geo.region.util.Lists;

import java.util.List;

public enum CountryEnum {
    AD("Andorra", "Andorra", "EU", "Andorra la Vella", Lists.newArrayList("376"), Lists.newArrayList("EUR"), Lists.newArrayList("ca")),
    AE("United Arab Emirates", "دولة الإمارات العربية المتحدة", "AS", "Abu Dhabi", Lists.newArrayList("971"), Lists.newArrayList("AED"), Lists.newArrayList("ar")),
    AF("Afghanistan", "افغانستان", "AS", "Kabul", Lists.newArrayList("93"), Lists.newArrayList("AFN"), Lists.newArrayList("ps", "uz", "tk")),
    AG("Antigua and Barbuda", "Antigua and Barbuda", "NA", "Saint John's", Lists.newArrayList("1268"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    AI("Anguilla", "Anguilla", "NA", "The Valley", Lists.newArrayList("1264"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    AL("Albania", "Shqipëria", "EU", "Tirana", Lists.newArrayList("355"), Lists.newArrayList("ALL"), Lists.newArrayList("sq")),
    AM("Armenia", "Հայաստան", "AS", "Yerevan", Lists.newArrayList("374"), Lists.newArrayList("AMD"), Lists.newArrayList("hy", "ru")),
    AO("Angola", "Angola", "AF", "Luanda", Lists.newArrayList("244"), Lists.newArrayList("AOA"), Lists.newArrayList("pt")),
    AQ("Antarctica", "Antarctica", "AN", "", Lists.newArrayList("672"), Lists.newArrayList(), Lists.newArrayList()),
    AR("Argentina", "Argentina", "SA", "Buenos Aires", Lists.newArrayList("54"), Lists.newArrayList("ARS"), Lists.newArrayList("es", "gn")),
    AS("American Samoa", "American Samoa", "OC", "Pago Pago", Lists.newArrayList("1684"), Lists.newArrayList("USD"), Lists.newArrayList("en", "sm")),
    AT("Austria", "Österreich", "EU", "Vienna", Lists.newArrayList("43"), Lists.newArrayList("EUR"), Lists.newArrayList("de")),
    AU("Australia", "Australia", "OC", "Canberra", Lists.newArrayList("61"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    AW("Aruba", "Aruba", "NA", "Oranjestad", Lists.newArrayList("297"), Lists.newArrayList("AWG"), Lists.newArrayList("nl", "pa")),
    AX("Åland", "Åland", "EU", "Mariehamn", Lists.newArrayList("358"), Lists.newArrayList("EUR"), Lists.newArrayList("sv")),
    AZ("Azerbaijan", "Azərbaycan", "AS", "Baku", Lists.newArrayList("994"), Lists.newArrayList("AZN"), Lists.newArrayList("az")),
    BA("Bosnia and Herzegovina", "Bosna i Hercegovina", "EU", "Sarajevo", Lists.newArrayList("387"), Lists.newArrayList("BAM"), Lists.newArrayList("bs", "hr", "sr")),
    BB("Barbados", "Barbados", "NA", "Bridgetown", Lists.newArrayList("1246"), Lists.newArrayList("BBD"), Lists.newArrayList("en")),
    BD("Bangladesh", "Bangladesh", "AS", "Dhaka", Lists.newArrayList("880"), Lists.newArrayList("BDT"), Lists.newArrayList("bn")),
    BE("Belgium", "België", "EU", "Brussels", Lists.newArrayList("32"), Lists.newArrayList("EUR"), Lists.newArrayList("nl", "fr", "de")),
    BF("Burkina Faso", "Burkina Faso", "AF", "Ouagadougou", Lists.newArrayList("226"), Lists.newArrayList("XOF"), Lists.newArrayList("fr", "ff")),
    BG("Bulgaria", "България", "EU", "Sofia", Lists.newArrayList("359"), Lists.newArrayList("BGN"), Lists.newArrayList("bg")),
    BH("Bahrain", "‏البحرين", "AS", "Manama", Lists.newArrayList("973"), Lists.newArrayList("BHD"), Lists.newArrayList("ar")),
    BI("Burundi", "Burundi", "AF", "Bujumbura", Lists.newArrayList("257"), Lists.newArrayList("BIF"), Lists.newArrayList("fr", "rn")),
    BJ("Benin", "Bénin", "AF", "Porto-Novo", Lists.newArrayList("229"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    BL("Saint Barthélemy", "Saint-Barthélemy", "NA", "Gustavia", Lists.newArrayList("590"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    BM("Bermuda", "Bermuda", "NA", "Hamilton", Lists.newArrayList("1441"), Lists.newArrayList("BMD"), Lists.newArrayList("en")),
    BN("Brunei", "Negara Brunei Darussalam", "AS", "Bandar Seri Begawan", Lists.newArrayList("673"), Lists.newArrayList("BND"), Lists.newArrayList("ms")),
    BO("Bolivia", "Bolivia", "SA", "Sucre", Lists.newArrayList("591"), Lists.newArrayList("BOB", "BOV"), Lists.newArrayList("es", "ay", "qu")),
    BQ("Bonaire", "Bonaire", "NA", "Kralendijk", Lists.newArrayList("5997"), Lists.newArrayList("USD"), Lists.newArrayList("nl")),
    BR("Brazil", "Brasil", "SA", "Brasília", Lists.newArrayList("55"), Lists.newArrayList("BRL"), Lists.newArrayList("pt")),
    BS("Bahamas", "Bahamas", "NA", "Nassau", Lists.newArrayList("1242"), Lists.newArrayList("BSD"), Lists.newArrayList("en")),
    BT("Bhutan", "ʼbrug-yul", "AS", "Thimphu", Lists.newArrayList("975"), Lists.newArrayList("BTN", "INR"), Lists.newArrayList("dz")),
    BV("Bouvet Island", "Bouvetøya", "AN", "", Lists.newArrayList("47"), Lists.newArrayList("NOK"), Lists.newArrayList("no", "nb", "nn")),
    BW("Botswana", "Botswana", "AF", "Gaborone", Lists.newArrayList("267"), Lists.newArrayList("BWP"), Lists.newArrayList("en", "tn")),
    BY("Belarus", "Белару́сь", "EU", "Minsk", Lists.newArrayList("375"), Lists.newArrayList("BYN"), Lists.newArrayList("be", "ru")),
    BZ("Belize", "Belize", "NA", "Belmopan", Lists.newArrayList("501"), Lists.newArrayList("BZD"), Lists.newArrayList("en", "es")),
    CA("Canada", "Canada", "NA", "Ottawa", Lists.newArrayList("1"), Lists.newArrayList("CAD"), Lists.newArrayList("en", "fr")),
    CC("Cocos [Keeling] Islands", "Cocos (Keeling) Islands", "AS", "West Island", Lists.newArrayList("61"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    CD("Democratic Republic of the Congo", "République démocratique du Congo", "AF", "Kinshasa", Lists.newArrayList("243"), Lists.newArrayList("CDF"), Lists.newArrayList("fr", "ln", "kg", "sw", "lu")),
    CF("Central African Republic", "Ködörösêse tî Bêafrîka", "AF", "Bangui", Lists.newArrayList("236"), Lists.newArrayList("XAF"), Lists.newArrayList("fr", "sg")),
    CG("Republic of the Congo", "République du Congo", "AF", "Brazzaville", Lists.newArrayList("242"), Lists.newArrayList("XAF"), Lists.newArrayList("fr", "ln")),
    CH("Switzerland", "Schweiz", "EU", "Bern", Lists.newArrayList("41"), Lists.newArrayList("CHE", "CHF", "CHW"), Lists.newArrayList("de", "fr", "it")),
    CI("Ivory Coast", "Côte d'Ivoire", "AF", "Yamoussoukro", Lists.newArrayList("225"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    CK("Cook Islands", "Cook Islands", "OC", "Avarua", Lists.newArrayList("682"), Lists.newArrayList("NZD"), Lists.newArrayList("en")),
    CL("Chile", "Chile", "SA", "Santiago", Lists.newArrayList("56"), Lists.newArrayList("CLF", "CLP"), Lists.newArrayList("es")),
    CM("Cameroon", "Cameroon", "AF", "Yaoundé", Lists.newArrayList("237"), Lists.newArrayList("XAF"), Lists.newArrayList("en", "fr")),
    CN("China", "中国", "AS", "Beijing", Lists.newArrayList("86"), Lists.newArrayList("CNY"), Lists.newArrayList("zh")),
    CO("Colombia", "Colombia", "SA", "Bogotá", Lists.newArrayList("57"), Lists.newArrayList("COP"), Lists.newArrayList("es")),
    CR("Costa Rica", "Costa Rica", "NA", "San José", Lists.newArrayList("506"), Lists.newArrayList("CRC"), Lists.newArrayList("es")),
    CU("Cuba", "Cuba", "NA", "Havana", Lists.newArrayList("53"), Lists.newArrayList("CUC", "CUP"), Lists.newArrayList("es")),
    CV("Cape Verde", "Cabo Verde", "AF", "Praia", Lists.newArrayList("238"), Lists.newArrayList("CVE"), Lists.newArrayList("pt")),
    CW("Curacao", "Curaçao", "NA", "Willemstad", Lists.newArrayList("5999"), Lists.newArrayList("ANG"), Lists.newArrayList("nl", "pa", "en")),
    CX("Christmas Island", "Christmas Island", "AS", "Flying Fish Cove", Lists.newArrayList("61"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    CY("Cyprus", "Κύπρος", "EU", "Nicosia", Lists.newArrayList("357"), Lists.newArrayList("EUR"), Lists.newArrayList("el", "tr", "hy")),
    CZ("Czech Republic", "Česká republika", "EU", "Prague", Lists.newArrayList("420"), Lists.newArrayList("CZK"), Lists.newArrayList("cs")),
    DE("Germany", "Deutschland", "EU", "Berlin", Lists.newArrayList("49"), Lists.newArrayList("EUR"), Lists.newArrayList("de")),
    DJ("Djibouti", "Djibouti", "AF", "Djibouti", Lists.newArrayList("253"), Lists.newArrayList("DJF"), Lists.newArrayList("fr", "ar")),
    DK("Denmark", "Danmark", "EU", "Copenhagen", Lists.newArrayList("45"), Lists.newArrayList("DKK"), Lists.newArrayList("da")),
    DM("Dominica", "Dominica", "NA", "Roseau", Lists.newArrayList("1767"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    DO("Dominican Republic", "República Dominicana", "NA", "Santo Domingo", Lists.newArrayList("1809", "1829", "1849"), Lists.newArrayList("DOP"), Lists.newArrayList("es")),
    DZ("Algeria", "الجزائر", "AF", "Algiers", Lists.newArrayList("213"), Lists.newArrayList("DZD"), Lists.newArrayList("ar")),
    EC("Ecuador", "Ecuador", "SA", "Quito", Lists.newArrayList("593"), Lists.newArrayList("USD"), Lists.newArrayList("es")),
    EE("Estonia", "Eesti", "EU", "Tallinn", Lists.newArrayList("372"), Lists.newArrayList("EUR"), Lists.newArrayList("et")),
    EG("Egypt", "مصر‎", "AF", "Cairo", Lists.newArrayList("20"), Lists.newArrayList("EGP"), Lists.newArrayList("ar")),
    EH("Western Sahara", "الصحراء الغربية", "AF", "El Aaiún", Lists.newArrayList("212"), Lists.newArrayList("MAD", "DZD", "MRU"), Lists.newArrayList("es")),
    ER("Eritrea", "ኤርትራ", "AF", "Asmara", Lists.newArrayList("291"), Lists.newArrayList("ERN"), Lists.newArrayList("ti", "ar", "en")),
    ES("Spain", "España", "EU", "Madrid", Lists.newArrayList("34"), Lists.newArrayList("EUR"), Lists.newArrayList("es", "eu", "ca", "gl", "oc")),
    ET("Ethiopia", "ኢትዮጵያ", "AF", "Addis Ababa", Lists.newArrayList("251"), Lists.newArrayList("ETB"), Lists.newArrayList("am")),
    FI("Finland", "Suomi", "EU", "Helsinki", Lists.newArrayList("358"), Lists.newArrayList("EUR"), Lists.newArrayList("fi", "sv")),
    FJ("Fiji", "Fiji", "OC", "Suva", Lists.newArrayList("679"), Lists.newArrayList("FJD"), Lists.newArrayList("en", "fj", "hi", "ur")),
    FK("Falkland Islands", "Falkland Islands", "SA", "Stanley", Lists.newArrayList("500"), Lists.newArrayList("FKP"), Lists.newArrayList("en")),
    FM("Micronesia", "Micronesia", "OC", "Palikir", Lists.newArrayList("691"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    FO("Faroe Islands", "Føroyar", "EU", "Tórshavn", Lists.newArrayList("298"), Lists.newArrayList("DKK"), Lists.newArrayList("fo")),
    FR("France", "France", "EU", "Paris", Lists.newArrayList("33"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    GA("Gabon", "Gabon", "AF", "Libreville", Lists.newArrayList("241"), Lists.newArrayList("XAF"), Lists.newArrayList("fr")),
    GB("United Kingdom", "United Kingdom", "EU", "London", Lists.newArrayList("44"), Lists.newArrayList("GBP"), Lists.newArrayList("en")),
    GD("Grenada", "Grenada", "NA", "St. George's", Lists.newArrayList("1473"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    GE("Georgia", "საქართველო", "AS", "Tbilisi", Lists.newArrayList("995"), Lists.newArrayList("GEL"), Lists.newArrayList("ka")),
    GF("French Guiana", "Guyane française", "SA", "Cayenne", Lists.newArrayList("594"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    GG("Guernsey", "Guernsey", "EU", "St. Peter Port", Lists.newArrayList("44"), Lists.newArrayList("GBP"), Lists.newArrayList("en", "fr")),
    GH("Ghana", "Ghana", "AF", "Accra", Lists.newArrayList("233"), Lists.newArrayList("GHS"), Lists.newArrayList("en")),
    GI("Gibraltar", "Gibraltar", "EU", "Gibraltar", Lists.newArrayList("350"), Lists.newArrayList("GIP"), Lists.newArrayList("en")),
    GL("Greenland", "Kalaallit Nunaat", "NA", "Nuuk", Lists.newArrayList("299"), Lists.newArrayList("DKK"), Lists.newArrayList("kl")),
    GM("Gambia", "Gambia", "AF", "Banjul", Lists.newArrayList("220"), Lists.newArrayList("GMD"), Lists.newArrayList("en")),
    GN("Guinea", "Guinée", "AF", "Conakry", Lists.newArrayList("224"), Lists.newArrayList("GNF"), Lists.newArrayList("fr", "ff")),
    GP("Guadeloupe", "Guadeloupe", "NA", "Basse-Terre", Lists.newArrayList("590"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    GQ("Equatorial Guinea", "Guinea Ecuatorial", "AF", "Malabo", Lists.newArrayList("240"), Lists.newArrayList("XAF"), Lists.newArrayList("es", "fr")),
    GR("Greece", "Ελλάδα", "EU", "Athens", Lists.newArrayList("30"), Lists.newArrayList("EUR"), Lists.newArrayList("el")),
    GS("South Georgia and the South Sandwich Islands", "South Georgia", "AN", "King Edward Point", Lists.newArrayList("500"), Lists.newArrayList("GBP"), Lists.newArrayList("en")),
    GT("Guatemala", "Guatemala", "NA", "Guatemala City", Lists.newArrayList("502"), Lists.newArrayList("GTQ"), Lists.newArrayList("es")),
    GU("Guam", "Guam", "OC", "Hagåtña", Lists.newArrayList("1671"), Lists.newArrayList("USD"), Lists.newArrayList("en", "ch", "es")),
    GW("Guinea-Bissau", "Guiné-Bissau", "AF", "Bissau", Lists.newArrayList("245"), Lists.newArrayList("XOF"), Lists.newArrayList("pt")),
    GY("Guyana", "Guyana", "SA", "Georgetown", Lists.newArrayList("592"), Lists.newArrayList("GYD"), Lists.newArrayList("en")),
    HK("Hong Kong", "香港", "AS", "City of Victoria", Lists.newArrayList("852"), Lists.newArrayList("HKD"), Lists.newArrayList("zh", "en")),
    HM("Heard Island and McDonald Islands", "Heard Island and McDonald Islands", "AN", "", Lists.newArrayList("61"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    HN("Honduras", "Honduras", "NA", "Tegucigalpa", Lists.newArrayList("504"), Lists.newArrayList("HNL"), Lists.newArrayList("es")),
    HR("Croatia", "Hrvatska", "EU", "Zagreb", Lists.newArrayList("385"), Lists.newArrayList("HRK"), Lists.newArrayList("hr")),
    HT("Haiti", "Haïti", "NA", "Port-au-Prince", Lists.newArrayList("509"), Lists.newArrayList("HTG", "USD"), Lists.newArrayList("fr", "ht")),
    HU("Hungary", "Magyarország", "EU", "Budapest", Lists.newArrayList("36"), Lists.newArrayList("HUF"), Lists.newArrayList("hu")),
    ID("Indonesia", "Indonesia", "AS", "Jakarta", Lists.newArrayList("62"), Lists.newArrayList("IDR"), Lists.newArrayList("id")),
    IE("Ireland", "Éire", "EU", "Dublin", Lists.newArrayList("353"), Lists.newArrayList("EUR"), Lists.newArrayList("ga", "en")),
    IL("Israel", "יִשְׂרָאֵל", "AS", "Jerusalem", Lists.newArrayList("972"), Lists.newArrayList("ILS"), Lists.newArrayList("he", "ar")),
    IM("Isle of Man", "Isle of Man", "EU", "Douglas", Lists.newArrayList("44"), Lists.newArrayList("GBP"), Lists.newArrayList("en", "gv")),
    IN("India", "भारत", "AS", "New Delhi", Lists.newArrayList("91"), Lists.newArrayList("INR"), Lists.newArrayList("hi", "en")),
    IO("British Indian Ocean Territory", "British Indian Ocean Territory", "AS", "Diego Garcia", Lists.newArrayList("246"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    IQ("Iraq", "العراق", "AS", "Baghdad", Lists.newArrayList("964"), Lists.newArrayList("IQD"), Lists.newArrayList("ar", "ku")),
    IR("Iran", "ایران", "AS", "Tehran", Lists.newArrayList("98"), Lists.newArrayList("IRR"), Lists.newArrayList("fa")),
    IS("Iceland", "Ísland", "EU", "Reykjavik", Lists.newArrayList("354"), Lists.newArrayList("ISK"), Lists.newArrayList("is")),
    IT("Italy", "Italia", "EU", "Rome", Lists.newArrayList("39"), Lists.newArrayList("EUR"), Lists.newArrayList("it")),
    JE("Jersey", "Jersey", "EU", "Saint Helier", Lists.newArrayList("44"), Lists.newArrayList("GBP"), Lists.newArrayList("en", "fr")),
    JM("Jamaica", "Jamaica", "NA", "Kingston", Lists.newArrayList("1876"), Lists.newArrayList("JMD"), Lists.newArrayList("en")),
    JO("Jordan", "الأردن", "AS", "Amman", Lists.newArrayList("962"), Lists.newArrayList("JOD"), Lists.newArrayList("ar")),
    JP("Japan", "日本", "AS", "Tokyo", Lists.newArrayList("81"), Lists.newArrayList("JPY"), Lists.newArrayList("ja")),
    KE("Kenya", "Kenya", "AF", "Nairobi", Lists.newArrayList("254"), Lists.newArrayList("KES"), Lists.newArrayList("en", "sw")),
    KG("Kyrgyzstan", "Кыргызстан", "AS", "Bishkek", Lists.newArrayList("996"), Lists.newArrayList("KGS"), Lists.newArrayList("ky", "ru")),
    KH("Cambodia", "Kâmpŭchéa", "AS", "Phnom Penh", Lists.newArrayList("855"), Lists.newArrayList("KHR"), Lists.newArrayList("km")),
    KI("Kiribati", "Kiribati", "OC", "South Tarawa", Lists.newArrayList("686"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    KM("Comoros", "Komori", "AF", "Moroni", Lists.newArrayList("269"), Lists.newArrayList("KMF"), Lists.newArrayList("ar", "fr")),
    KN("Saint Kitts and Nevis", "Saint Kitts and Nevis", "NA", "Basseterre", Lists.newArrayList("1869"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    KP("North Korea", "북한", "AS", "Pyongyang", Lists.newArrayList("850"), Lists.newArrayList("KPW"), Lists.newArrayList("ko")),
    KR("South Korea", "대한민국", "AS", "Seoul", Lists.newArrayList("82"), Lists.newArrayList("KRW"), Lists.newArrayList("ko")),
    KW("Kuwait", "الكويت", "AS", "Kuwait City", Lists.newArrayList("965"), Lists.newArrayList("KWD"), Lists.newArrayList("ar")),
    KY("Cayman Islands", "Cayman Islands", "NA", "George Town", Lists.newArrayList("1345"), Lists.newArrayList("KYD"), Lists.newArrayList("en")),
    KZ("Kazakhstan", "Қазақстан", "AS", "Astana", Lists.newArrayList("76", "77"), Lists.newArrayList("KZT"), Lists.newArrayList("kk", "ru")),
    LA("Laos", "ສປປລາວ", "AS", "Vientiane", Lists.newArrayList("856"), Lists.newArrayList("LAK"), Lists.newArrayList("lo")),
    LB("Lebanon", "لبنان", "AS", "Beirut", Lists.newArrayList("961"), Lists.newArrayList("LBP"), Lists.newArrayList("ar", "fr")),
    LC("Saint Lucia", "Saint Lucia", "NA", "Castries", Lists.newArrayList("1758"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    LI("Liechtenstein", "Liechtenstein", "EU", "Vaduz", Lists.newArrayList("423"), Lists.newArrayList("CHF"), Lists.newArrayList("de")),
    LK("Sri Lanka", "śrī laṃkāva", "AS", "Colombo", Lists.newArrayList("94"), Lists.newArrayList("LKR"), Lists.newArrayList("si", "ta")),
    LR("Liberia", "Liberia", "AF", "Monrovia", Lists.newArrayList("231"), Lists.newArrayList("LRD"), Lists.newArrayList("en")),
    LS("Lesotho", "Lesotho", "AF", "Maseru", Lists.newArrayList("266"), Lists.newArrayList("LSL", "ZAR"), Lists.newArrayList("en", "st")),
    LT("Lithuania", "Lietuva", "EU", "Vilnius", Lists.newArrayList("370"), Lists.newArrayList("EUR"), Lists.newArrayList("lt")),
    LU("Luxembourg", "Luxembourg", "EU", "Luxembourg", Lists.newArrayList("352"), Lists.newArrayList("EUR"), Lists.newArrayList("fr", "de", "lb")),
    LV("Latvia", "Latvija", "EU", "Riga", Lists.newArrayList("371"), Lists.newArrayList("EUR"), Lists.newArrayList("lv")),
    LY("Libya", "‏ليبيا", "AF", "Tripoli", Lists.newArrayList("218"), Lists.newArrayList("LYD"), Lists.newArrayList("ar")),
    MA("Morocco", "المغرب", "AF", "Rabat", Lists.newArrayList("212"), Lists.newArrayList("MAD"), Lists.newArrayList("ar")),
    MC("Monaco", "Monaco", "EU", "Monaco", Lists.newArrayList("377"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    MD("Moldova", "Moldova", "EU", "Chișinău", Lists.newArrayList("373"), Lists.newArrayList("MDL"), Lists.newArrayList("ro")),
    ME("Montenegro", "Црна Гора", "EU", "Podgorica", Lists.newArrayList("382"), Lists.newArrayList("EUR"), Lists.newArrayList("sr", "bs", "sq", "hr")),
    MF("Saint Martin", "Saint-Martin", "NA", "Marigot", Lists.newArrayList("590"), Lists.newArrayList("EUR"), Lists.newArrayList("en", "fr", "nl")),
    MG("Madagascar", "Madagasikara", "AF", "Antananarivo", Lists.newArrayList("261"), Lists.newArrayList("MGA"), Lists.newArrayList("fr", "mg")),
    MH("Marshall Islands", "M̧ajeļ", "OC", "Majuro", Lists.newArrayList("692"), Lists.newArrayList("USD"), Lists.newArrayList("en", "mh")),
    MK("North Macedonia", "Северна Македонија", "EU", "Skopje", Lists.newArrayList("389"), Lists.newArrayList("MKD"), Lists.newArrayList("mk")),
    ML("Mali", "Mali", "AF", "Bamako", Lists.newArrayList("223"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    MM("Myanmar [Burma]", "မြန်မာ", "AS", "Naypyidaw", Lists.newArrayList("95"), Lists.newArrayList("MMK"), Lists.newArrayList("my")),
    MN("Mongolia", "Монгол улс", "AS", "Ulan Bator", Lists.newArrayList("976"), Lists.newArrayList("MNT"), Lists.newArrayList("mn")),
    MO("Macao", "澳門", "AS", "", Lists.newArrayList("853"), Lists.newArrayList("MOP"), Lists.newArrayList("zh", "pt")),
    MP("Northern Mariana Islands", "Northern Mariana Islands", "OC", "Saipan", Lists.newArrayList("1670"), Lists.newArrayList("USD"), Lists.newArrayList("en", "ch")),
    MQ("Martinique", "Martinique", "NA", "Fort-de-France", Lists.newArrayList("596"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    MR("Mauritania", "موريتانيا", "AF", "Nouakchott", Lists.newArrayList("222"), Lists.newArrayList("MRU"), Lists.newArrayList("ar")),
    MS("Montserrat", "Montserrat", "NA", "Plymouth", Lists.newArrayList("1664"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    MT("Malta", "Malta", "EU", "Valletta", Lists.newArrayList("356"), Lists.newArrayList("EUR"), Lists.newArrayList("mt", "en")),
    MU("Mauritius", "Maurice", "AF", "Port Louis", Lists.newArrayList("230"), Lists.newArrayList("MUR"), Lists.newArrayList("en")),
    MV("Maldives", "Maldives", "AS", "Malé", Lists.newArrayList("960"), Lists.newArrayList("MVR"), Lists.newArrayList("dv")),
    MW("Malawi", "Malawi", "AF", "Lilongwe", Lists.newArrayList("265"), Lists.newArrayList("MWK"), Lists.newArrayList("en", "ny")),
    MX("Mexico", "México", "NA", "Mexico City", Lists.newArrayList("52"), Lists.newArrayList("MXN"), Lists.newArrayList("es")),
    MY("Malaysia", "Malaysia", "AS", "Kuala Lumpur", Lists.newArrayList("60"), Lists.newArrayList("MYR"), Lists.newArrayList("ms")),
    MZ("Mozambique", "Moçambique", "AF", "Maputo", Lists.newArrayList("258"), Lists.newArrayList("MZN"), Lists.newArrayList("pt")),
    NA("Namibia", "Namibia", "AF", "Windhoek", Lists.newArrayList("264"), Lists.newArrayList("NAD", "ZAR"), Lists.newArrayList("en", "af")),
    NC("New Caledonia", "Nouvelle-Calédonie", "OC", "Nouméa", Lists.newArrayList("687"), Lists.newArrayList("XPF"), Lists.newArrayList("fr")),
    NE("Niger", "Niger", "AF", "Niamey", Lists.newArrayList("227"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    NF("Norfolk Island", "Norfolk Island", "OC", "Kingston", Lists.newArrayList("672"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    NG("Nigeria", "Nigeria", "AF", "Abuja", Lists.newArrayList("234"), Lists.newArrayList("NGN"), Lists.newArrayList("en")),
    NI("Nicaragua", "Nicaragua", "NA", "Managua", Lists.newArrayList("505"), Lists.newArrayList("NIO"), Lists.newArrayList("es")),
    NL("Netherlands", "Nederland", "EU", "Amsterdam", Lists.newArrayList("31"), Lists.newArrayList("EUR"), Lists.newArrayList("nl")),
    NO("Norway", "Norge", "EU", "Oslo", Lists.newArrayList("47"), Lists.newArrayList("NOK"), Lists.newArrayList("no", "nb", "nn")),
    NP("Nepal", "नपल", "AS", "Kathmandu", Lists.newArrayList("977"), Lists.newArrayList("NPR"), Lists.newArrayList("ne")),
    NR("Nauru", "Nauru", "OC", "Yaren", Lists.newArrayList("674"), Lists.newArrayList("AUD"), Lists.newArrayList("en", "na")),
    NU("Niue", "Niuē", "OC", "Alofi", Lists.newArrayList("683"), Lists.newArrayList("NZD"), Lists.newArrayList("en")),
    NZ("New Zealand", "New Zealand", "OC", "Wellington", Lists.newArrayList("64"), Lists.newArrayList("NZD"), Lists.newArrayList("en", "mi")),
    OM("Oman", "عمان", "AS", "Muscat", Lists.newArrayList("968"), Lists.newArrayList("OMR"), Lists.newArrayList("ar")),
    PA("Panama", "Panamá", "NA", "Panama City", Lists.newArrayList("507"), Lists.newArrayList("PAB", "USD"), Lists.newArrayList("es")),
    PE("Peru", "Perú", "SA", "Lima", Lists.newArrayList("51"), Lists.newArrayList("PEN"), Lists.newArrayList("es")),
    PF("French Polynesia", "Polynésie française", "OC", "Papeetē", Lists.newArrayList("689"), Lists.newArrayList("XPF"), Lists.newArrayList("fr")),
    PG("Papua New Guinea", "Papua Niugini", "OC", "Port Moresby", Lists.newArrayList("675"), Lists.newArrayList("PGK"), Lists.newArrayList("en")),
    PH("Philippines", "Pilipinas", "AS", "Manila", Lists.newArrayList("63"), Lists.newArrayList("PHP"), Lists.newArrayList("en")),
    PK("Pakistan", "Pakistan", "AS", "Islamabad", Lists.newArrayList("92"), Lists.newArrayList("PKR"), Lists.newArrayList("en", "ur")),
    PL("Poland", "Polska", "EU", "Warsaw", Lists.newArrayList("48"), Lists.newArrayList("PLN"), Lists.newArrayList("pl")),
    PM("Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", "NA", "Saint-Pierre", Lists.newArrayList("508"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    PN("Pitcairn Islands", "Pitcairn Islands", "OC", "Adamstown", Lists.newArrayList("64"), Lists.newArrayList("NZD"), Lists.newArrayList("en")),
    PR("Puerto Rico", "Puerto Rico", "NA", "San Juan", Lists.newArrayList("1787", "1939"), Lists.newArrayList("USD"), Lists.newArrayList("es", "en")),
    PS("Palestine", "فلسطين", "AS", "Ramallah", Lists.newArrayList("970"), Lists.newArrayList("ILS"), Lists.newArrayList("ar")),
    PT("Portugal", "Portugal", "EU", "Lisbon", Lists.newArrayList("351"), Lists.newArrayList("EUR"), Lists.newArrayList("pt")),
    PW("Palau", "Palau", "OC", "Ngerulmud", Lists.newArrayList("680"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    PY("Paraguay", "Paraguay", "SA", "Asunción", Lists.newArrayList("595"), Lists.newArrayList("PYG"), Lists.newArrayList("es", "gn")),
    QA("Qatar", "قطر", "AS", "Doha", Lists.newArrayList("974"), Lists.newArrayList("QAR"), Lists.newArrayList("ar")),
    RE("Réunion", "La Réunion", "AF", "Saint-Denis", Lists.newArrayList("262"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    RO("Romania", "România", "EU", "Bucharest", Lists.newArrayList("40"), Lists.newArrayList("RON"), Lists.newArrayList("ro")),
    RS("Serbia", "Србија", "EU", "Belgrade", Lists.newArrayList("381"), Lists.newArrayList("RSD"), Lists.newArrayList("sr")),
    RU("Russia", "Россия", "EU", "Moscow", Lists.newArrayList("7"), Lists.newArrayList("RUB"), Lists.newArrayList("ru")),
    RW("Rwanda", "Rwanda", "AF", "Kigali", Lists.newArrayList("250"), Lists.newArrayList("RWF"), Lists.newArrayList("rw", "en", "fr")),
    SA("Saudi Arabia", "العربية السعودية", "AS", "Riyadh", Lists.newArrayList("966"), Lists.newArrayList("SAR"), Lists.newArrayList("ar")),
    SB("Solomon Islands", "Solomon Islands", "OC", "Honiara", Lists.newArrayList("677"), Lists.newArrayList("SBD"), Lists.newArrayList("en")),
    SC("Seychelles", "Seychelles", "AF", "Victoria", Lists.newArrayList("248"), Lists.newArrayList("SCR"), Lists.newArrayList("fr", "en")),
    SD("Sudan", "السودان", "AF", "Khartoum", Lists.newArrayList("249"), Lists.newArrayList("SDG"), Lists.newArrayList("ar", "en")),
    SE("Sweden", "Sverige", "EU", "Stockholm", Lists.newArrayList("46"), Lists.newArrayList("SEK"), Lists.newArrayList("sv")),
    SG("Singapore", "Singapore", "AS", "Singapore", Lists.newArrayList("65"), Lists.newArrayList("SGD"), Lists.newArrayList("en", "ms", "ta", "zh")),
    SH("Saint Helena", "Saint Helena", "AF", "Jamestown", Lists.newArrayList("290"), Lists.newArrayList("SHP"), Lists.newArrayList("en")),
    SI("Slovenia", "Slovenija", "EU", "Ljubljana", Lists.newArrayList("386"), Lists.newArrayList("EUR"), Lists.newArrayList("sl")),
    SJ("Svalbard and Jan Mayen", "Svalbard og Jan Mayen", "EU", "Longyearbyen", Lists.newArrayList("4779"), Lists.newArrayList("NOK"), Lists.newArrayList("no")),
    SK("Slovakia", "Slovensko", "EU", "Bratislava", Lists.newArrayList("421"), Lists.newArrayList("EUR"), Lists.newArrayList("sk")),
    SL("Sierra Leone", "Sierra Leone", "AF", "Freetown", Lists.newArrayList("232"), Lists.newArrayList("SLL"), Lists.newArrayList("en")),
    SM("San Marino", "San Marino", "EU", "City of San Marino", Lists.newArrayList("378"), Lists.newArrayList("EUR"), Lists.newArrayList("it")),
    SN("Senegal", "Sénégal", "AF", "Dakar", Lists.newArrayList("221"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    SO("Somalia", "Soomaaliya", "AF", "Mogadishu", Lists.newArrayList("252"), Lists.newArrayList("SOS"), Lists.newArrayList("so", "ar")),
    SR("Suriname", "Suriname", "SA", "Paramaribo", Lists.newArrayList("597"), Lists.newArrayList("SRD"), Lists.newArrayList("nl")),
    SS("South Sudan", "South Sudan", "AF", "Juba", Lists.newArrayList("211"), Lists.newArrayList("SSP"), Lists.newArrayList("en")),
    ST("São Tomé and Príncipe", "São Tomé e Príncipe", "AF", "São Tomé", Lists.newArrayList("239"), Lists.newArrayList("STN"), Lists.newArrayList("pt")),
    SV("El Salvador", "El Salvador", "NA", "San Salvador", Lists.newArrayList("503"), Lists.newArrayList("SVC", "USD"), Lists.newArrayList("es")),
    SX("Sint Maarten", "Sint Maarten", "NA", "Philipsburg", Lists.newArrayList("1721"), Lists.newArrayList("ANG"), Lists.newArrayList("nl", "en")),
    SY("Syria", "سوريا", "AS", "Damascus", Lists.newArrayList("963"), Lists.newArrayList("SYP"), Lists.newArrayList("ar")),
    SZ("Swaziland", "Swaziland", "AF", "Lobamba", Lists.newArrayList("268"), Lists.newArrayList("SZL"), Lists.newArrayList("en", "ss")),
    TC("Turks and Caicos Islands", "Turks and Caicos Islands", "NA", "Cockburn Town", Lists.newArrayList("1649"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    TD("Chad", "Tchad", "AF", "N'Djamena", Lists.newArrayList("235"), Lists.newArrayList("XAF"), Lists.newArrayList("fr", "ar")),
    TF("French Southern Territories", "Territoire des Terres australes et antarctiques fr", "AN", "Port-aux-Français", Lists.newArrayList("262"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    TG("Togo", "Togo", "AF", "Lomé", Lists.newArrayList("228"), Lists.newArrayList("XOF"), Lists.newArrayList("fr")),
    TH("Thailand", "ประเทศไทย", "AS", "Bangkok", Lists.newArrayList("66"), Lists.newArrayList("THB"), Lists.newArrayList("th")),
    TJ("Tajikistan", "Тоҷикистон", "AS", "Dushanbe", Lists.newArrayList("992"), Lists.newArrayList("TJS"), Lists.newArrayList("tg", "ru")),
    TK("Tokelau", "Tokelau", "OC", "Fakaofo", Lists.newArrayList("690"), Lists.newArrayList("NZD"), Lists.newArrayList("en")),
    TL("East Timor", "Timor-Leste", "OC", "Dili", Lists.newArrayList("670"), Lists.newArrayList("USD"), Lists.newArrayList("pt")),
    TM("Turkmenistan", "Türkmenistan", "AS", "Ashgabat", Lists.newArrayList("993"), Lists.newArrayList("TMT"), Lists.newArrayList("tk", "ru")),
    TN("Tunisia", "تونس", "AF", "Tunis", Lists.newArrayList("216"), Lists.newArrayList("TND"), Lists.newArrayList("ar")),
    TO("Tonga", "Tonga", "OC", "Nuku'alofa", Lists.newArrayList("676"), Lists.newArrayList("TOP"), Lists.newArrayList("en", "to")),
    TR("Turkey", "Türkiye", "AS", "Ankara", Lists.newArrayList("90"), Lists.newArrayList("TRY"), Lists.newArrayList("tr")),
    TT("Trinidad and Tobago", "Trinidad and Tobago", "NA", "Port of Spain", Lists.newArrayList("1868"), Lists.newArrayList("TTD"), Lists.newArrayList("en")),
    TV("Tuvalu", "Tuvalu", "OC", "Funafuti", Lists.newArrayList("688"), Lists.newArrayList("AUD"), Lists.newArrayList("en")),
    TW("Taiwan", "臺灣", "AS", "Taipei", Lists.newArrayList("886"), Lists.newArrayList("TWD"), Lists.newArrayList("zh")),
    TZ("Tanzania", "Tanzania", "AF", "Dodoma", Lists.newArrayList("255"), Lists.newArrayList("TZS"), Lists.newArrayList("sw", "en")),
    UA("Ukraine", "Україна", "EU", "Kyiv", Lists.newArrayList("380"), Lists.newArrayList("UAH"), Lists.newArrayList("uk")),
    UG("Uganda", "Uganda", "AF", "Kampala", Lists.newArrayList("256"), Lists.newArrayList("UGX"), Lists.newArrayList("en", "sw")),
    UM("U.S. Minor Outlying Islands", "United States Minor Outlying Islands", "OC", "", Lists.newArrayList("1"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    US("United States", "United States", "NA", "Washington D.C.", Lists.newArrayList("1"), Lists.newArrayList("USD", "USN", "USS"), Lists.newArrayList("en")),
    UY("Uruguay", "Uruguay", "SA", "Montevideo", Lists.newArrayList("598"), Lists.newArrayList("UYI", "UYU"), Lists.newArrayList("es")),
    UZ("Uzbekistan", "O‘zbekiston", "AS", "Tashkent", Lists.newArrayList("998"), Lists.newArrayList("UZS"), Lists.newArrayList("uz", "ru")),
    VA("Vatican City", "Vaticano", "EU", "Vatican City", Lists.newArrayList("379"), Lists.newArrayList("EUR"), Lists.newArrayList("it", "la")),
    VC("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "NA", "Kingstown", Lists.newArrayList("1784"), Lists.newArrayList("XCD"), Lists.newArrayList("en")),
    VE("Venezuela", "Venezuela", "SA", "Caracas", Lists.newArrayList("58"), Lists.newArrayList("VES"), Lists.newArrayList("es")),
    VG("British Virgin Islands", "British Virgin Islands", "NA", "Road Town", Lists.newArrayList("1284"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    VI("U.S. Virgin Islands", "United States Virgin Islands", "NA", "Charlotte Amalie", Lists.newArrayList("1340"), Lists.newArrayList("USD"), Lists.newArrayList("en")),
    VN("Vietnam", "Việt Nam", "AS", "Hanoi", Lists.newArrayList("84"), Lists.newArrayList("VND"), Lists.newArrayList("vi")),
    VU("Vanuatu", "Vanuatu", "OC", "Port Vila", Lists.newArrayList("678"), Lists.newArrayList("VUV"), Lists.newArrayList("bi", "en", "fr")),
    WF("Wallis and Futuna", "Wallis et Futuna", "OC", "Mata-Utu", Lists.newArrayList("681"), Lists.newArrayList("XPF"), Lists.newArrayList("fr")),
    WS("Samoa", "Samoa", "OC", "Apia", Lists.newArrayList("685"), Lists.newArrayList("WST"), Lists.newArrayList("sm", "en")),
    XK("Kosovo", "Republika e Kosovës", "EU", "Pristina", Lists.newArrayList("377", "381", "383", "386"), Lists.newArrayList("EUR"), Lists.newArrayList("sq", "sr")),
    YE("Yemen", "اليَمَن", "AS", "Sana'a", Lists.newArrayList("967"), Lists.newArrayList("YER"), Lists.newArrayList("ar")),
    YT("Mayotte", "Mayotte", "AF", "Mamoudzou", Lists.newArrayList("262"), Lists.newArrayList("EUR"), Lists.newArrayList("fr")),
    ZA("South Africa", "South Africa", "AF", "Pretoria", Lists.newArrayList("27"), Lists.newArrayList("ZAR"), Lists.newArrayList("af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu")),
    ZM("Zambia", "Zambia", "AF", "Lusaka", Lists.newArrayList("260"), Lists.newArrayList("ZMW"), Lists.newArrayList("en")),
    ZW("Zimbabwe", "Zimbabwe", "AF", "Harare", Lists.newArrayList("263"), Lists.newArrayList("USD", "ZAR", "BWP", "GBP", "AUD", "CNY", "INR", "JPY"), Lists.newArrayList("en", "sn", "nd"));

    private final String name;
    private final String nativeName;
    private final String continent;
    private final String capital;
    private final List<String> phone;
    private final List<String> currency;
    private final List<String> languages;

    CountryEnum(String name, String nativeName, String continent, String capital, List<String> phone, List<String> currency, List<String> languages) {
        this.name = name;
        this.nativeName = nativeName;
        this.continent = continent;
        this.capital = capital;
        this.phone = phone;
        this.currency = currency;
        this.languages = languages;
    }

    public String getName() {
        return name;
    }

    public String getNativeName() {
        return nativeName;
    }

    public String getContinent() {
        return continent;
    }

    public String getCapital() {
        return capital;
    }

    public List<String> getPhone() {
        return phone;
    }

    public List<String> getCurrency() {
        return currency;
    }

    public List<String> getLanguages() {
        return languages;
    }


}
